### ISSUE TITLE
server does not send any data even when dtf files are present

### ISSUE THREAD

**Issue by Swoorup** [0b01/tectonicdb#13]
Even though a dtf database are present for a specific pair in the filesystem, the server does not respond back with any data.

```
--> GET 1
ERR: Requested 1 but only have 0.
```

**Comment by rickyhan** [comment]
Type INFO to get the name of the db. Then `USE dbname`

**Comment by Swoorup** [comment]
I did exactly that.
INFO
USE bt_btcneo

Still no results

**Comment by rickyhan** [comment]
Did you use the -f flag?
